<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HIBAIL56180" name="RunnerClass.Runner" tests="6" failures="2" timestamp="21 Apr 2020 08:10:01 GMT" time="232.751" errors="0">
  <testcase name="scenario" time="41.537" classname="RunnerClass.Runner"/>
  <testcase name="runScenario" time="33.234" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="35.671" classname="RunnerClass.Runner">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
]]>
    </failure>
  </testcase> <!-- scenario -->
  <testcase name="runScenario" time="40.830" classname="RunnerClass.Runner">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at Definition.Test123.userIsAlreadyInTheLoginPage(Test123.java:26)
at ✽.user is already in the login page(file:///E:/NoticeperiodSelenium/cucumberreports/src/main/java/Features/Test123.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="40.616" classname="RunnerClass.Runner"/>
  <testcase name="scenario" time="40.863" classname="RunnerClass.Runner"/>
</testsuite> <!-- RunnerClass.Runner -->
